{{-- {!!Form::open(['url'=>'tours','methode'=>'POST'])!!}
{!!Form::text('Nom_tour','',['placeholder'=>'Entrez le nom de tour'])!!}<br>
{!!Form::text('nmbr_jour','',['placeholder'=>'Entrez le nombre de jour'])!!}<br>
{!!Form::select('lieu',[
    "AF"=>'Afghanistan',
    "ZA"=>'Afrique du sud',
    "AX"=>'Åland, îles',
    "AL"=>'Albanie',
    "DZ"=>'Algérie',
    "DE"=>'Allemagne',
    "AD"=>'Andorre',
    "AO"=>'Angola',
    "AI"=>'Anguilla',
    "AQ"=>'Antarctique',
    "AG"=>'Antigua et barbuda',
    "SA"=>'Arabie saoudite',
    "AR"=>'Argentine',
    "AM"=>'Arménie',
    "AW"=>'Aruba',
    "AU"=>'Australie',
    "AT"=>'Autriche',
    "AZ"=>'Azerbaïdjan',
    "BS"=>'Bahamas',
    "BH"=>'Bahreïn',
    "BD"=>'Bangladesh',
    "BB"=>'Barbade',
    "BY"=>'Bélarus',
    "BE"=>'Belgique',
    "BZ"=>'Belize',
    "BJ"=>'Bénin',
    "BM"=>'Bermudes',
    "BT"=>'Bhoutan',
    "BO"=>"olivie,l'état plurinational de",
    "BQ"=>'Bonaire, saint eustache et saba',
    "BA"=>'Bosnie herzégovine',
    "BW"=>'Botswana',
    "BV"=>'Bouvet, île',
    "BR"=>'Brésil,',
    "BN"=>'Brunei darussalam',
    "BG"=>'Bulgarie',
    "BF"=>'Burkina faso',
    "BI"=>'Burundi',
    "KY"=>'Caïmans, îles',
    "KH"=>'Cambodge',
    "CM"=>'Cameroun',
    "CA"=>'Canada',
    "CV"=>'Cap vert',
    "CF"=>'Centrafricaine, république',
    "CL"=>'Chili',
    "CN"=>'Chine',
    "CX"=>'Christmas, île',
    "CY"=>'Chypre',
    "CC"=>'Cocos (keeling), îles',
    "CO"=>'Colombie',
    "KM"=>'Comores',
    "CG"=>'Congo',
    "CD"=>'Congo, la république démocratique du',
    "CK"=>'Cook, îles',
    "KR"=>'Corée, république de',
    "KP"=>'Corée, république populaire démocratique de',
    "CR"=>'Costa rica',
    "CI"=>"Côte d'ivoire",
    "HR"=>'Croatie',
    "CU"=>'Cuba',
    "CW"=>'Curaçao',
    "DK"=>'Danemark',
    "DJ"=>'Djibouti',
    "DO"=>'Dominicaine, république',
    "DM"=>'Dominique',
    "EG"=>'Égypte',
    "SV"=>'El salvador',
    "AE"=>'Émirats arabes unis',
    "EC"=>'Équateur',
    "ER"=>'Érythrée',
    "ES"=>'Espagne',
    "EE"=>'Estonie',
    "US"=>'États unis',
    "ET"=>'Éthiopie',
    "FK"=>'Falkland, îles (malvinas)',
    "FO"=>'Féroé, îles',
    "FJ"=>'Fidji',
    "FI"=>'Finlande',
    "FR"=>'France',
    "GA"=>'Gabon',
    "GM"=>'Gambie',
    "GS"=>'Géorgie du sud et les îles sandwich du sud',
    "GH"=>'Ghana',
    "GI"=>'Gibraltar',
    "GR"=>'Grèce',
    "GD"=>'Grenade',
    "GL"=>'Groenland',
    "GP"=>'Guadeloupe',
    "GU"=>'Guam',
    "GT"=>'Guatemala',
    "GG"=>'Guernesey',
    "GN"=>'Guinée',
    "GW"=>'Guinée bissau',
    "GQ"=>'Guinée équatoriale',
    "GY"=>'Guyana',
    "GF"=>'Guyane française',
    "HT"=>'Haïti',
    "HM"=>'Heard et îles macdonald, île',
    "HN"=>'Honduras',
    "HK"=>'Hong kong',
    "HU"=>'Hongrie',
    "IM"=>'Île de man',
    "UM"=>'Îles mineures éloignées des états unis',
    "VG"=>'Îles vierges britanniques',
    "VI"=>'Îles vierges des états unis',
    "IN"=>'Inde',
    "ID"=>'Indonésie',
    "IR"=>'Iran, république islamique',
    "IQ"=>'Iraq',
    "IE"=>'Irlande',
    "IS"=>'Islande',
    "IL"=>'Israël',
    "IT"=>'Italie',
    "JM"=>'Jamaïque',
    "JP"=>'Japon',
    "JE"=>'Jersey',
    "JO"=>'Jordanie',
    "KZ"=>'Kazakhstan',
    "KE"=>'Kenya',
    "KG"=>'Kirghizistan',
    "KI"=>'Kiribati',
    "KW"=>'Koweït',
    "LA"=>'Lao, république démocratique populaire',
    "LS"=>'Lesotho',
    "LV"=>'Lettonie',
    "LB"=>'Liban',
    "LR"=>'Libéria',
    "LY"=>'Libye',
    "LI"=>'Liechtenstein',
    "LT"=>'Lituanie',
    "LU"=>'Luxembourg',
    "MO"=>'Macao',
    "MK"=>"Macédoine, l'ex république yougoslave de",
    "MG"=>'Madagascar',
    "MY"=>'Malaisie',
    "MW"=>'Malawi',
    "MV"=>'Maldives',
    "ML"=>'Mali',
    "MT"=>'Malte',
    "MP"=>'Mariannes du nord, îles',
    "MA"=>'Maroc',
    "MH"=>'Marshall, îles',
    "MQ"=>'Martinique',
    "MU"=>'Maurice',
    "MR"=>'Mauritanie',
    "YT"=>'Mayotte',
    "MX"=>'Mexique',
    "FM"=>'Micronésie, états fédérés de',
    "MD"=>'Moldova, république de',
    "MC"=>'Monaco',
    "MN"=>'Mongolie',
    "ME"=>'Monténégro',
    "MS"=>'Montserrat',
    "MZ"=>'Mozambique',
    "MM"=>'Myanmar',
    "NA"=>'Namibie',
    "NR"=>'Nauru',
    "NP"=>'Népal',
    "NI"=>'Nicaragua',
    "NE"=>'Niger',
    "NG"=>'Nigéria',
    "NU"=>'Niué',
    "NF"=>'Norfolk, île',
    "NO"=>'Norvège',
    "NC"=>'Nouvelle calédonie',
    "NZ"=>'Nouvelle zélande',
    "IO"=>'Océan indien, territoire britannique de l',
    "OM"=>'Oman',
    "UG"=>'Ouganda',
    "UZ"=>'Ouzbékistan',
    "PK"=>'Pakistan',
    "PS"=>'Palestinien occupé, territoire',
    "PA"=>'Panama',
    "PG"=>'Papouasie nouvelle guinée',
    "PY"=>'Paraguay',
    "NL"=>'Pays bas',
    "PE"=>'Pérou',
    "PH"=>'Philippines',
    "PN"=>'Pitcairn',
    "PL"=>'Pologne',
    "PF"=>'Polynésie ',
    "PR"=>'Porto rico',
    "PT"=>'Portugal',
    "QA"=>'Qatar',
    "RE"=>'Réunion',
    "RO"=>'Roumanie',
    "GB"=>'Royaume uni',
    "RU"=>'Russie, fédération de',
    "RW"=>'Rwanda',
    "EH"=>'Sahara occidental',
    "BL"=>'Saint barthélemy',
    "SH"=>'Sainte hélène, ascension et tristan da cunha',
    "LC"=>'Sainte lucie',
    "KN"=>'Saint kitts et nevis',
    "SM"=>'Saint marin',
    "MF"=>'Saint martin(partie française)',
    "SX"=>'Saint martin (partie néerlandaise)',
    "PM"=>'Saint pierre et miquelon',
    "VA"=>'Saint siège (état de la cité du vatican)',
    "VC"=>'Saint vincent et les grenadines',
    "SB"=>'Salomon, îles',
    "WS"=>'Samoa',
    "AS"=>'Samoa américaines',
    "ST"=>'Sao tomé et principe',
    "SN"=>'Sénégal',
    "RS"=>'Serbie',
    "SC"=>'Seychelles',
    "SL"=>'Sierra leone',
    "SG"=>'Singapour',
    "SK"=>'Slovaquie',
    "SI"=>'Slovénie',
    "SO"=>'Somalie',
    "SD"=>'Soudan',
    "SS"=>'Soudan du sud',
    "LK"=>'Sri lanka',
    "SE"=>'Suède',
    "CH"=>'Suisse',
    "SR"=>'Suriname',
    "SJ"=>'Svalbard et île jan mayen',
    "SZ"=>'Swaziland',
    "SY"=>'Syrienne, république arabe',
    "TJ"=>'Tadjikistan',
    "TW"=>'Taïwan, province de chine',
    "TZ"=>'Tanzanie, république unie de',
    "TD"=>'Tchad',
    "CZ"=>'Tchèque, république',
    "TF"=>'Terres australes françaises',
    "TH"=>'Thaïlande',
    "TL"=>'Timor leste',
    "TG"=>'Togo',
    "TK"=>'Tokelau',
    "TO"=>'Tonga',
    "TT"=>'Trinité et tobago',
    "TN"=>'Tunisie',
    "TM"=>'Turkménistan',
    "TC"=>'Turks et caïcos, îles',
    "TR"=>'Turquie',
    "TV"=>'Tuvalu',
    "UA"=>'Ukraine',
    "UY"=>'Uruguay',
    "VU"=>'Vanuatu',
    "VE"=>'Venezuela, république bolivarienne du',
    "VN"=>'Viet nam',
    "WF"=>"Wallis et' futuna",
    "YE"=>'Yémen'])!!}<br>
{!!Form::select('langue',[
        "ang"=>"englich",
        "ara"=>"arabic",
        "fre"=>"french"
])!!}
    {!! Form::submit('valider', ['class' => 'btn btn-info pull-right']) !!}
{!!Form::close()!!} --}}
<form action="{{url('tours')}}" method="POST">
    @csrf
    <input type="text" name="Nom_tour"  placeholder="Entrez le nom de tour"><br>
<input type="text" name="nmbr_jour"  placeholder="Entrez le nombre de jour"><br>
<select name="lieu" >
        <option value="Afghanistan">Afghanistan
        <option value="Afrique du sud">Afrique du sud
        <option value="Åland, îles">Åland, îles
        <option value="Albanie">Albanie
        <option value="Algérie">Algérie
        <option value="Allemagne">Allemagne
        <option value="Andorre">Andorre
        <option value="Angola">Angola
        <option value="Anguilla">Anguilla
        <option value="Antarctique">Antarctique
        <option value="Antigua et barbuda">Antigua et barbuda
        <option value="Arabie saoudite">Arabie saoudite
        <option value="Argentine">Argentine
        <option value="Arménie">Arménie
        <option value="Aruba">Aruba
        <option value="Australie">Australie
        <option value="Autriche">Autriche
        <option value="Azerbaïdjan">Azerbaïdjan
        <option value="Bahamas">Bahamas
        <option value="Bahreïn">Bahreïn
        <option value="Bangladesh">Bangladesh
        <option value="Barbade">Barbade
        <option value="Bélarus">Bélarus
        <option value="Belgique">Belgique
        <option value="Belize">Belize
        <option value="Bénin">Bénin
        <option value="Bermudes">Bermudes
        <option value="Botswana">Botswana
        <option value="Bouvet, île">Bouvet, île
        <option value="Brésil">Brésil
        <option value="Bulgarie">Bulgarie
        <option value="Burkina faso">Burkina faso
        <option value="Burundi">Burundi
        <option value="Caïmans, îles">Caïmans, îles
        <option value="Cambodge">Cambodge
        <option value="Cameroun">Cameroun
        <option value="Canada">Canada
        <option value="Cap vert">Cap vert
        <option value="Centrafricaine, république">Centrafricaine, république
        <option value="Chili">Chili
        <option value="Chine">Chine
        <option value="Christmas, île">Christmas, île
        <option value="Chypre">Chypre
        <option value="Cocos (keeling), îles">Cocos (keeling), îles
        <option value="Colombie">Colombie
        <option value="Comores">Comores
        <option value="Congo">Congo
        <option value="Cook, îles">Cook, îles
        <option value="Costa rica">Costa rica
        <option value="Côte d'ivoire">Côte d'ivoire
        <option value="Croatie">Croatie
        <option value="Cuba">Cuba
        <option value="Curaçao">Curaçao
        <option value="Danemark">Danemark
        <option value="Djibouti">Djibouti
        <option value="Dominicaine, république">Dominicaine, république
        <option value="Dominique">Dominique
        <option value="Égypte">Égypte
        <option value="El salvador">El salvador
        <option value="Émirats arabes unis">Émirats arabes unis
        <option value="Équateur">Équateur
        <option value="Érythrée">Érythrée
        <option value="Espagne">Espagne
        <option value="Estonie">Estonie
        <option value="États unis">États unis
        <option value="Éthiopie">Éthiopie
        <option value="Fidji">Fidji
        <option value="Finlande">Finlande
        <option value="France">France
        <option value="Gabon">Gabon
        <option value="Gambie">Gambie
        <option value="Géorgie">Géorgie
        <option value="Ghana">Ghana
        <option value="Gibraltar">Gibraltar
        <option value="Grèce">Grèce
        <option value="Grenade">Grenade
        <option value="Groenland">Groenland
        <option value="Guadeloupe">Guadeloupe
        <option value="Guam">Guam
        <option value="Guatemala">Guatemala
        <option value="Guernesey">Guernesey
        <option value="Guinée">Guinée
        <option value="Guinée bissau">Guinée bissau
        <option value="Guinée équatoriale">Guinée équatoriale
        <option value="Guyana">Guyana
        <option value="Guyane française">Guyane française
        <option value="Haïti">Haïti
        <option value="Honduras">Honduras
        <option value="Hong kong">Hong kong
        <option value="Hongrie">Hongrie
        <option value="Inde">Inde
        <option value="Indonésie">Indonésie
        <option value="Iran, république islamique">Iran, république islamique 
        <option value="Iraq">Iraq
        <option value="Irlande">Irlande
        <option value="Islande">Islande
        <option value="Israël">Israël
        <option value="Italie">Italie
        <option value="Jamaïque">Jamaïque
        <option value="Japon">Japon
        <option value="Jersey">Jersey
        <option value="Jordanie">Jordanie
        <option value="Kazakhstan">Kazakhstan
        <option value="Kenya">Kenya
        <option value="Kirghizistan">Kirghizistan
        <option value="Kiribati">Kiribati
        <option value="Lesotho">Lesotho
        <option value="Lettonie">Lettonie
        <option value="Liban">Liban
        <option value="Libéria">Libéria
        <option value="Libye">Libye
</select><br>
<select name="langue" >
    <option value="englich">englich</option>
    <option value="arabic">arabic</option>
    <option value="freanch">freanch</option>
</select><br>
<input type="submit"  value="valider">
</form>
